### ISSUE TITLE
Wrong namespace

### ISSUE THREAD

**Issue by ewallah** [dmitriim/moodle-block_verify_certs#24]
PHPUnit reports a failure:

```
vendor/bin/phpunit --colors --no-coverage --testsuite core_privacy_testsuite

core_privacy\privacy\provider_test::test_all_providers_compliant with data set "block_verify_certs" ('block_verify_certs', 'block_verify_certs\privacy\provider')
Failed asserting that false is true.

privacy/tests/privacy/provider_test.php:179
lib/phpunit/classes/advanced_testcase.php:81
```

When changing the namespace from `namespace block_verify_certs;` to `namespace block_verify_certs\privacy;` in [provider.php](https://github.com/dmitriim/moodle-block_verify_certs/blob/MOODLE_401_STABLE/classes/privacy/provider.php#L17) the error is gone.

**Comment by dmitriim** [comment]
Good catch @ewallah . Should be an easy fix. PR is always welcome!

**Comment by dmitriim** [comment]
Fixed. Thanks @ewallah !
